//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OpaccWebservice
{
    using Opacc.Client.Session.Exceptions;
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestContext", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws")]
    public partial class RequestContext : object
    {
        
        private string InstallationField;
        
        private string InstallationVersionField;
        
        private string ConsumerField;
        
        private string ClientIdField;
        
        private string UserIdField;
        
        private string PasswordField;
        
        private string PermissionField;
        
        private string DataLanguageIdField;
        
        private string UserInterfaceLanguageIdField;
        
        private string SessionField;
        
        private string ImpersonatorIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Installation
        {
            get
            {
                return this.InstallationField;
            }
            set
            {
                this.InstallationField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string InstallationVersion
        {
            get
            {
                return this.InstallationVersionField;
            }
            set
            {
                this.InstallationVersionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Consumer
        {
            get
            {
                return this.ConsumerField;
            }
            set
            {
                this.ConsumerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ClientId
        {
            get
            {
                return this.ClientIdField;
            }
            set
            {
                this.ClientIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string UserId
        {
            get
            {
                return this.UserIdField;
            }
            set
            {
                this.UserIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Permission
        {
            get
            {
                return this.PermissionField;
            }
            set
            {
                this.PermissionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string DataLanguageId
        {
            get
            {
                return this.DataLanguageIdField;
            }
            set
            {
                this.DataLanguageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string UserInterfaceLanguageId
        {
            get
            {
                return this.UserInterfaceLanguageIdField;
            }
            set
            {
                this.UserInterfaceLanguageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string Session
        {
            get
            {
                return this.SessionField;
            }
            set
            {
                this.SessionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public string ImpersonatorId
        {
            get
            {
                return this.ImpersonatorIdField;
            }
            set
            {
                this.ImpersonatorIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Data", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class Data : object
    {
        
        private string StringField;
        
        private byte[] BytesField;
        
        private OpaccWebservice.Data[] ArrayField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string String
        {
            get
            {
                return this.StringField;
            }
            set
            {
                this.StringField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public byte[] Bytes
        {
            get
            {
                return this.BytesField;
            }
            set
            {
                this.BytesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public OpaccWebservice.Data[] Array
        {
            get
            {
                return this.ArrayField;
            }
            set
            {
                this.ArrayField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseInfo", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws")]
    public partial class ResponseInfo : object
    {
        
        private bool SuccessfulField;
        
        private string MessageIdField;
        
        private string MlsMessageTextField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Successful
        {
            get
            {
                return this.SuccessfulField;
            }
            set
            {
                this.SuccessfulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public string MessageId
        {
            get
            {
                return this.MessageIdField;
            }
            set
            {
                this.MessageIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public string MlsMessageText
        {
            get
            {
                return this.MlsMessageTextField;
            }
            set
            {
                this.MlsMessageTextField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestSet", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class RequestSet : object
    {
        
        private string LabelField;
        
        private OpaccWebservice.RequestWithinSet[] RequestsField;
        
        private OpaccWebservice.Data ProcessingInstructionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpaccWebservice.RequestWithinSet[] Requests
        {
            get
            {
                return this.RequestsField;
            }
            set
            {
                this.RequestsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public OpaccWebservice.Data ProcessingInstructions
        {
            get
            {
                return this.ProcessingInstructionsField;
            }
            set
            {
                this.ProcessingInstructionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RequestWithinSet", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class RequestWithinSet : object
    {
        
        private string NameField;
        
        private string PortIdField;
        
        private string OperationIdField;
        
        private OpaccWebservice.RequestContext ContextField;
        
        private OpaccWebservice.Data DataField;
        
        private OpaccWebservice.Data ProcessingInstructionsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortId
        {
            get
            {
                return this.PortIdField;
            }
            set
            {
                this.PortIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string OperationId
        {
            get
            {
                return this.OperationIdField;
            }
            set
            {
                this.OperationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public OpaccWebservice.RequestContext Context
        {
            get
            {
                return this.ContextField;
            }
            set
            {
                this.ContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public OpaccWebservice.Data Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public OpaccWebservice.Data ProcessingInstructions
        {
            get
            {
                return this.ProcessingInstructionsField;
            }
            set
            {
                this.ProcessingInstructionsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseSet", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class ResponseSet : object
    {
        
        private OpaccWebservice.ResponseInfo InfoField;
        
        private OpaccWebservice.ResponseWithinSet[] ResponsesField;
        
        private OpaccWebservice.Data ProcessingInfosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpaccWebservice.ResponseInfo Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpaccWebservice.ResponseWithinSet[] Responses
        {
            get
            {
                return this.ResponsesField;
            }
            set
            {
                this.ResponsesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public OpaccWebservice.Data ProcessingInfos
        {
            get
            {
                return this.ProcessingInfosField;
            }
            set
            {
                this.ProcessingInfosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResponseWithinSet", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class ResponseWithinSet : object
    {
        
        private string NameField;
        
        private OpaccWebservice.ResponseInfo InfoField;
        
        private OpaccWebservice.Data DataField;
        
        private OpaccWebservice.Data ProcessingInfosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public OpaccWebservice.ResponseInfo Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public OpaccWebservice.Data Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public OpaccWebservice.Data ProcessingInfos
        {
            get
            {
                return this.ProcessingInfosField;
            }
            set
            {
                this.ProcessingInfosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatRequestData", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class FlatRequestData : object
    {
        
        private string[] ParametersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Parameters
        {
            get
            {
                return this.ParametersField;
            }
            set
            {
                this.ParametersField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatResponseData", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class FlatResponseData : object
    {
        
        private int RowCountField;
        
        private int ColumnCountField;
        
        private OpaccWebservice.Column[] ColumnsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowCount
        {
            get
            {
                return this.RowCountField;
            }
            set
            {
                this.RowCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int ColumnCount
        {
            get
            {
                return this.ColumnCountField;
            }
            set
            {
                this.ColumnCountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public OpaccWebservice.Column[] Columns
        {
            get
            {
                return this.ColumnsField;
            }
            set
            {
                this.ColumnsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Column", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class Column : object
    {
        
        private string NameField;
        
        private string[] RowsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] Rows
        {
            get
            {
                return this.RowsField;
            }
            set
            {
                this.RowsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatRequestSet", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class FlatRequestSet : object
    {
        
        private string LabelField;
        
        private OpaccWebservice.FlatRequestWithinSet[] RequestsField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Label
        {
            get
            {
                return this.LabelField;
            }
            set
            {
                this.LabelField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpaccWebservice.FlatRequestWithinSet[] Requests
        {
            get
            {
                return this.RequestsField;
            }
            set
            {
                this.RequestsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatRequestWithinSet", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class FlatRequestWithinSet : object
    {
        
        private string NameField;
        
        private string PortIdField;
        
        private string OperationIdField;
        
        private OpaccWebservice.RequestContext ContextField;
        
        private OpaccWebservice.FlatRequestData DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PortId
        {
            get
            {
                return this.PortIdField;
            }
            set
            {
                this.PortIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string OperationId
        {
            get
            {
                return this.OperationIdField;
            }
            set
            {
                this.OperationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public OpaccWebservice.RequestContext Context
        {
            get
            {
                return this.ContextField;
            }
            set
            {
                this.ContextField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public OpaccWebservice.FlatRequestData Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatResponseSet", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class FlatResponseSet : object
    {
        
        private OpaccWebservice.ResponseInfo InfoField;
        
        private OpaccWebservice.FlatResponseWithinSet[] ResponsesField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpaccWebservice.ResponseInfo Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public OpaccWebservice.FlatResponseWithinSet[] Responses
        {
            get
            {
                return this.ResponsesField;
            }
            set
            {
                this.ResponsesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FlatResponseWithinSet", Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic")]
    public partial class FlatResponseWithinSet : object
    {
        
        private string NameField;
        
        private OpaccWebservice.ResponseInfo InfoField;
        
        private OpaccWebservice.FlatResponseData DataField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public OpaccWebservice.ResponseInfo Info
        {
            get
            {
                return this.InfoField;
            }
            set
            {
                this.InfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public OpaccWebservice.FlatResponseData Data
        {
            get
            {
                return this.DataField;
            }
            set
            {
                this.DataField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", ConfigurationName="OpaccWebservice.Generic")]
    public interface Generic
    {
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/Request", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/RequestRespons" +
            "e")]
        System.Threading.Tasks.Task<OpaccWebservice.RequestResponse> RequestAsync(OpaccWebservice.RequestRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/RequestWithPro" +
            "cInstrAndInfos", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/RequestWithPro" +
            "cInstrAndInfosResponse")]
        System.Threading.Tasks.Task<OpaccWebservice.RequestWithProcInstrAndInfosResponse> RequestWithProcInstrAndInfosAsync(OpaccWebservice.RequestWithProcInstrAndInfosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/RequestsWithPr" +
            "ocInstrAndInfos", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/RequestsWithPr" +
            "ocInstrAndInfosResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ResponseSet")]
        System.Threading.Tasks.Task<OpaccWebservice.ResponseSet> RequestsWithProcInstrAndInfosAsync(OpaccWebservice.RequestSet RequestSet);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/FlatRequest", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/FlatRequestRes" +
            "ponse")]
        System.Threading.Tasks.Task<OpaccWebservice.FlatRequestResponse> FlatRequestAsync(OpaccWebservice.FlatRequestRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/FlatRequests", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/FlatRequestsRe" +
            "sponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ResponseSet")]
        System.Threading.Tasks.Task<OpaccWebservice.FlatResponseSet> FlatRequestsAsync(OpaccWebservice.FlatRequestSet RequestSet);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/FlatRequestWit" +
            "hStreamResponse", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/FlatRequestWit" +
            "hStreamResponseResponse")]
        System.Threading.Tasks.Task<System.IO.Stream> FlatRequestWithStreamResponseAsync(string PortId, string OperationId, OpaccWebservice.RequestContext RequestContext, OpaccWebservice.FlatRequestData RequestData, string StreamSelector, string StreamMimeType, string StreamMimeTypeSelector, string StreamName, string StreamNameSelector, bool StreamAsAttachment);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/EncryptPasswor" +
            "d", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/EncryptPasswor" +
            "dResponse")]
        System.Threading.Tasks.Task<string> EncryptPasswordAsync(string plainPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/StartSession", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/StartSessionRe" +
            "sponse")]
        System.Threading.Tasks.Task<string> StartSessionAsync(OpaccWebservice.RequestContext RequestContext);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/StopSession", ReplyAction="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic/Generic/StopSessionRes" +
            "ponse")]
        System.Threading.Tasks.Task StopSessionAsync(OpaccWebservice.RequestContext RequestContext);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Request", WrapperNamespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", IsWrapped=true)]
    public partial class RequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=0)]
        public string PortId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=1)]
        public string OperationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=2)]
        public OpaccWebservice.RequestContext RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=3)]
        public OpaccWebservice.Data RequestData;
        
        public RequestRequest()
        {
        }
        
        public RequestRequest(string PortId, string OperationId, OpaccWebservice.RequestContext RequestContext, OpaccWebservice.Data RequestData)
        {
            this.PortId = PortId;
            this.OperationId = OperationId;
            this.RequestContext = RequestContext;
            this.RequestData = RequestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestResponse", WrapperNamespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", IsWrapped=true)]
    public partial class RequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=0)]
        public OpaccWebservice.ResponseInfo ResponseInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=1)]
        public OpaccWebservice.Data ResponseData;
        
        public RequestResponse()
        {
        }
        
        public RequestResponse(OpaccWebservice.ResponseInfo ResponseInfo, OpaccWebservice.Data ResponseData)
        {
            this.ResponseInfo = ResponseInfo;
            this.ResponseData = ResponseData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestWithProcInstrAndInfos", WrapperNamespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", IsWrapped=true)]
    public partial class RequestWithProcInstrAndInfosRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=0)]
        public string PortId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=1)]
        public string OperationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=2)]
        public OpaccWebservice.RequestContext RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=3)]
        public OpaccWebservice.Data RequestData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=4)]
        public OpaccWebservice.Data ProcessingInstructions;
        
        public RequestWithProcInstrAndInfosRequest()
        {
        }
        
        public RequestWithProcInstrAndInfosRequest(string PortId, string OperationId, OpaccWebservice.RequestContext RequestContext, OpaccWebservice.Data RequestData, OpaccWebservice.Data ProcessingInstructions)
        {
            this.PortId = PortId;
            this.OperationId = OperationId;
            this.RequestContext = RequestContext;
            this.RequestData = RequestData;
            this.ProcessingInstructions = ProcessingInstructions;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="RequestWithProcInstrAndInfosResponse", WrapperNamespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", IsWrapped=true)]
    public partial class RequestWithProcInstrAndInfosResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=0)]
        public OpaccWebservice.ResponseInfo ResponseInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=1)]
        public OpaccWebservice.Data ResponseData;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=2)]
        public OpaccWebservice.Data ProcessingInfos;
        
        public RequestWithProcInstrAndInfosResponse()
        {
        }
        
        public RequestWithProcInstrAndInfosResponse(OpaccWebservice.ResponseInfo ResponseInfo, OpaccWebservice.Data ResponseData, OpaccWebservice.Data ProcessingInfos)
        {
            this.ResponseInfo = ResponseInfo;
            this.ResponseData = ResponseData;
            this.ProcessingInfos = ProcessingInfos;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FlatRequest", WrapperNamespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", IsWrapped=true)]
    public partial class FlatRequestRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=0)]
        public string PortId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=1)]
        public string OperationId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=2)]
        public OpaccWebservice.RequestContext RequestContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=3)]
        public OpaccWebservice.FlatRequestData RequestData;
        
        public FlatRequestRequest()
        {
        }
        
        public FlatRequestRequest(string PortId, string OperationId, OpaccWebservice.RequestContext RequestContext, OpaccWebservice.FlatRequestData RequestData)
        {
            this.PortId = PortId;
            this.OperationId = OperationId;
            this.RequestContext = RequestContext;
            this.RequestData = RequestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FlatRequestResponse", WrapperNamespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", IsWrapped=true)]
    public partial class FlatRequestResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=0)]
        public OpaccWebservice.ResponseInfo ResponseInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://www.opacc.com/Opacc/ServiceBus/Interface/Ws/Generic", Order=1)]
        public OpaccWebservice.FlatResponseData ResponseData;
        
        public FlatRequestResponse()
        {
        }
        
        public FlatRequestResponse(OpaccWebservice.ResponseInfo ResponseInfo, OpaccWebservice.FlatResponseData ResponseData)
        {
            this.ResponseInfo = ResponseInfo;
            this.ResponseData = ResponseData;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface GenericChannel : OpaccWebservice.Generic, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class GenericClient : System.ServiceModel.ClientBase<OpaccWebservice.Generic>, OpaccWebservice.Generic
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public GenericClient(string wsUrl) :
        base(GenericClient.GetDefaultBinding(), GenericClient.GetDefaultEndpointAddress(wsUrl))
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_Generic.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public System.Threading.Tasks.Task<OpaccWebservice.RequestResponse> RequestAsync(OpaccWebservice.RequestRequest request)
        {
            return base.Channel.RequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpaccWebservice.RequestWithProcInstrAndInfosResponse> RequestWithProcInstrAndInfosAsync(OpaccWebservice.RequestWithProcInstrAndInfosRequest request)
        {
            return base.Channel.RequestWithProcInstrAndInfosAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpaccWebservice.ResponseSet> RequestsWithProcInstrAndInfosAsync(OpaccWebservice.RequestSet RequestSet)
        {
            return base.Channel.RequestsWithProcInstrAndInfosAsync(RequestSet);
        }
        
        public System.Threading.Tasks.Task<OpaccWebservice.FlatRequestResponse> FlatRequestAsync(OpaccWebservice.FlatRequestRequest request)
        {
            return base.Channel.FlatRequestAsync(request);
        }
        
        public System.Threading.Tasks.Task<OpaccWebservice.FlatResponseSet> FlatRequestsAsync(OpaccWebservice.FlatRequestSet RequestSet)
        {
            return base.Channel.FlatRequestsAsync(RequestSet);
        }
        
        public System.Threading.Tasks.Task<System.IO.Stream> FlatRequestWithStreamResponseAsync(string PortId, string OperationId, OpaccWebservice.RequestContext RequestContext, OpaccWebservice.FlatRequestData RequestData, string StreamSelector, string StreamMimeType, string StreamMimeTypeSelector, string StreamName, string StreamNameSelector, bool StreamAsAttachment)
        {
            return base.Channel.FlatRequestWithStreamResponseAsync(PortId, OperationId, RequestContext, RequestData, StreamSelector, StreamMimeType, StreamMimeTypeSelector, StreamName, StreamNameSelector, StreamAsAttachment);
        }
        
        public System.Threading.Tasks.Task<string> EncryptPasswordAsync(string plainPassword)
        {
            return base.Channel.EncryptPasswordAsync(plainPassword);
        }
        
        public System.Threading.Tasks.Task<string> StartSessionAsync(OpaccWebservice.RequestContext RequestContext)
        {
            return base.Channel.StartSessionAsync(RequestContext);
        }
        
        public System.Threading.Tasks.Task StopSessionAsync(OpaccWebservice.RequestContext RequestContext)
        {
            return base.Channel.StopSessionAsync(RequestContext);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_Generic))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CustomBinding_Generic))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration, string wsUrl)
        {
            if (string.IsNullOrWhiteSpace(wsUrl))
                throw new OpaccSessionException("WebService URL is required");

            return new System.ServiceModel.EndpointAddress(wsUrl);
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GenericClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_Generic);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress(string wsUrl)
        {
            return GenericClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_Generic, wsUrl);
        }

        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_Generic,
            
            CustomBinding_Generic,
        }
    }
}
