namespace Opacc.Client;

/// <summary>
/// Marker interface for typed Opacc service request objects generated by <c>opacc-client scaffold</c>.
///
/// Implement this to use the strongly-typed <see cref="IOpaccClient.SendAsync{TRequest}"/> overload:
///   <code>await _client.SendAsync(new ArtSal_GetPriceRequest { ArtNo = "10100", CustNo = 1001 });</code>
/// </summary>
public interface IOpaccServiceRequest
{
    /// <summary>The target Opacc service (port + operation name).</summary>
    OpaccServiceId ServiceId { get; }
}
