using System.Text;
using Opacc.Client.Enums;

namespace Opacc.Client.CLI.Scaffold;

/// <summary>
/// Generiert C#-Quellcode für ein Opacc-Model aus GetInfoBoAttr-Daten.
/// </summary>
internal static class ModelGenerator
{
    /// <param name="boName">Name des BO, z.B. "SalDoc".</param>
    /// <param name="attributes">Attribute aus GetInfoBoAttr.</param>
    /// <param name="namespaceName">Ziel-Namespace.</param>
    /// <param name="defaultIndexNo">BoIdIndex aus GetInfoBo (Default-Index für Start-Key).</param>
    /// <param name="allIndexSegments">
    /// Alle Indices aus GetInfoBoIndex: indexNo → geordnete Liste von vollqualifizierten Segment-Expressions.
    /// </param>
    public static string Generate(
        string boName,
        List<BoAttrInfo> attributes,
        string namespaceName        = "GeneratedModels",
        int defaultIndexNo          = 1,
        Dictionary<int, List<string>>? allIndexSegments = null)
    {
        allIndexSegments ??= [];

        // Build reverse lookup: attrExpression → list of (indexNo, segmentNo)
        // so we can emit [BoId(indexNo, segmentNo)] per property
        var exprToKeys = new Dictionary<string, List<(int IndexNo, int SegmentNo)>>(
            StringComparer.OrdinalIgnoreCase);

        foreach (var (indexNo, segments) in allIndexSegments)
        {
            for (int seg = 0; seg < segments.Count; seg++)
            {
                var expr = segments[seg];
                if (!exprToKeys.TryGetValue(expr, out var keys))
                    exprToKeys[expr] = keys = [];
                keys.Add((indexNo, seg + 1)); // segmentNo is 1-based
            }
        }

        var sb = new StringBuilder();

        bool hasDateFields = attributes.Any(a => TypeMapper.Map(a.DataTypeCd, a.Format).DataTypeAnnotation != null);

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Opacc.Client;");
        sb.AppendLine("using Opacc.Client.Attributes;");
        if (hasDateFields)
            sb.AppendLine("using Opacc.Client.Enums;");
        sb.AppendLine();

        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();

        sb.AppendLine($"[Bo(\"{boName}\")]");
        sb.AppendLine($"[BoDefaultIndex({defaultIndexNo})]");
        sb.AppendLine($"public partial class {boName} : IOpaccModel");
        sb.AppendLine("{");

        var generatedNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        bool first = true;

        foreach (var attr in attributes)
        {
            var propName = ToPascalCase(attr.ShortName);
            if (string.IsNullOrWhiteSpace(propName))
                continue;

            // Deduplizierung
            var uniqueName = propName;
            int counter = 2;
            while (!generatedNames.Add(uniqueName))
                uniqueName = propName + counter++;
            propName = uniqueName;

            var mapped = TypeMapper.Map(attr.DataTypeCd, attr.Format);

            if (!first) sb.AppendLine();
            first = false;

            // Kommentar (nur wenn sinnvoller Inhalt)
            if (!string.IsNullOrWhiteSpace(attr.Description))
                sb.AppendLine($"    /// <summary>{EscapeXml(attr.Description)}</summary>");

            // [BoId(indexNo, segmentNo)] für jedes Index-Segment dieses Attributs
            if (exprToKeys.TryGetValue(attr.AttrExpression, out var indexKeys))
            {
                foreach (var (indexNo, segmentNo) in indexKeys.OrderBy(k => k.IndexNo))
                    sb.AppendLine($"    [BoId({indexNo}, {segmentNo})]");
            }

            // [BoPropertyNotAvailableInQuery] wenn GetInfoQuery ViewItemStateCd != "AV_PUB"
            if (attr.NotAvailableInQuery)
                sb.AppendLine("    [BoPropertyNotAvailableInQuery]");

            // [BoProperty] wenn Expression ≠ Konvention  ODER  DataType-Annotation nötig
            bool expressionDiffersFromConvention = ExpressionDiffersFromConvention(boName, attr, propName);
            bool needsDataType = mapped.DataTypeAnnotation != null;

            if (expressionDiffersFromConvention || needsDataType)
            {
                var fullExpr = attr.AttrExpression.Contains('.') ? attr.AttrExpression : $"{boName}.{attr.AttrExpression}";
                sb.Append($"    [BoProperty(\"{fullExpr}\"");
                if (needsDataType)
                    sb.Append($", OpaccDataType.{mapped.DataTypeAnnotation}");
                sb.AppendLine(")]");
            }

            // Property-Deklaration
            if (mapped.IsValueType)
                sb.AppendLine($"    public {mapped.ClrType} {propName} {{ get; set; }}");
            else
                sb.AppendLine($"    public {mapped.ClrType} {propName} {{ get; set; }} = {TypeMapper.DefaultValue(mapped.ClrType)};");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    private static bool ExpressionDiffersFromConvention(string boName, BoAttrInfo attr, string propName)
    {
        var convention = $"{boName}.{propName}";
        if (string.Equals(attr.AttrExpression, convention, StringComparison.OrdinalIgnoreCase))
            return false;
        if (!attr.AttrExpression.Contains('.') &&
            string.Equals(attr.AttrExpression, propName, StringComparison.OrdinalIgnoreCase))
            return false;
        return true;
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return name;

        var sb = new StringBuilder();
        bool nextUpper = true;

        foreach (char c in name)
        {
            if (c is '_' or '-' or ' ')
                nextUpper = true;
            else if (char.IsLetterOrDigit(c))
            {
                sb.Append(nextUpper ? char.ToUpper(c) : c);
                nextUpper = false;
            }
        }

        var result = sb.ToString();
        if (result.Length > 0)
            result = char.ToUpper(result[0]) + result[1..];

        return result switch
        {
            "Class"  => "Class_",
            "Object" => "Object_",
            "String" => "String_",
            "Int"    => "Int_",
            "Base"   => "Base_",
            "Event"  => "Event_",
            "Type"   => "Type_",
            "Ref"    => "Ref_",
            "Out"    => "Out_",
            "In"     => "In_",
            _        => result,
        };
    }

    private static string EscapeXml(string text) =>
        text.Replace("&", "&amp;").Replace("<", "&lt;").Replace(">", "&gt;");
}
