using System.Text;
using System.Text.RegularExpressions;

namespace Opacc.Client.CLI.Scaffold;

/// <summary>
/// Generiert eine statische OpaccService-Klasse mit allen verfügbaren Services als Konstanten.
///
/// Beispiel-Output:
///   public static class OpaccService
///   {
///       public static readonly OpaccServiceId ArtSal_GetPrice  = new("Biz",    "ArtSal_GetPrice");
///       public static readonly OpaccServiceId SalDoc_Process   = new("Biz",    "SalDoc_Process");
///       public static readonly OpaccServiceId System_RunScript = new("System", "System_RunScript");
///   }
/// </summary>
internal static class ServiceGenerator
{
    public static string Generate(IReadOnlyList<ServiceInfo> services, string namespaceName)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Opacc.Client;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Vordefinierte Opacc-Service-Konstanten für die Verwendung mit");
        sb.AppendLine("/// <c>_opaccClient.SendRawAsync(OpaccService.XYZ, new { ... })</c>.");
        sb.AppendLine("/// Generiert via <c>opacc-client scaffold</c>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class OpaccService");
        sb.AppendLine("{");

        // Gruppiert nach Port für Übersichtlichkeit
        var byPort = services
            .GroupBy(s => s.PortId)
            .OrderBy(g => g.Key);

        // Maximale Länge für Ausrichtung
        var maxLen = services.Count > 0
            ? services.Max(s => ToIdentifier(s.OperationId).Length)
            : 0;

        foreach (var group in byPort)
        {
            sb.AppendLine($"    // {group.Key}");

            foreach (var svc in group.OrderBy(s => s.OperationId))
            {
                var identifier = ToIdentifier(svc.OperationId);
                var padding    = new string(' ', maxLen - identifier.Length);
                sb.AppendLine(
                    $"    public static readonly OpaccServiceId {identifier}{padding} = new(\"{svc.PortId}\", \"{svc.OperationId}\");");
            }

            sb.AppendLine();
        }

        // Schliessende geschweifte Klammer (letzte Leerzeile entfernen)
        if (sb[^2] == '\n') sb.Length -= Environment.NewLine.Length;
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Konvertiert einen Service-Namen in einen gültigen C#-Bezeichner.
    /// "ArtSal_GetPrice" → "ArtSal_GetPrice" (meistens schon gültig)
    /// "123Service"      → "_123Service"     (führende Ziffer)
    /// "Some-Service"    → "Some_Service"    (Bindestriche)
    /// </summary>
    private static string ToIdentifier(string name)
    {
        // Ungültige Zeichen durch Unterstrich ersetzen
        var id = Regex.Replace(name, @"[^\w]", "_");

        // Führende Ziffer → Unterstrich davor
        if (id.Length > 0 && char.IsDigit(id[0]))
            id = "_" + id;

        return id;
    }
}
