using System.Text;
using System.Text.RegularExpressions;

namespace Opacc.Client.CLI.Scaffold;

/// <summary>
/// Generiert eine typisierte Request-Klasse für einen Opacc-Service.
///
/// Beispiel-Output für "ArtSal_GetPrice":
///   public sealed class ArtSal_GetPriceRequest : IOpaccServiceRequest
///   {
///       public OpaccServiceId ServiceId => new("Biz", "ArtSal_GetPrice");
///       public string?  ArtNo          { get; set; }
///       public int?     CustNo         { get; set; }
///       public decimal? Quantity       { get; set; }
///       ...
///   }
/// </summary>
internal static class ServiceRequestGenerator
{
    public static string? Generate(string serviceName, List<ServiceAoAttrInfo> attrs, string namespaceName)
    {
        // Only input parameters — skip result/output (RelationshipCd = "R")
        var inputAttrs = attrs.Where(a => a.RelationshipCd != "R").ToList();
        if (inputAttrs.Count == 0)
            return null;

        var className = ToClassName(serviceName);

        // Alignment padding
        var maxTypeLen = inputAttrs
            .Select(a => NullableClrType(a.DataTypeCd, a.Format).Length)
            .DefaultIfEmpty(0).Max();

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("using Opacc.Client;");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"public sealed class {className} : IOpaccServiceRequest");
        sb.AppendLine("{");
        sb.AppendLine($"    public OpaccServiceId ServiceId => new(\"Biz\", \"{serviceName}\");");
        sb.AppendLine();

        foreach (var attr in inputAttrs)
        {
            var clrType = NullableClrType(attr.DataTypeCd, attr.Format);
            var padding = new string(' ', maxTypeLen - clrType.Length);
            sb.AppendLine($"    public {clrType}{padding} {attr.Name} {{ get; set; }}");
        }

        sb.AppendLine("}");
        return sb.ToString();
    }

    /// <summary>
    /// Returns nullable C# type string for the given Opacc type/format.
    /// All service parameters are treated as optional (nullable).
    /// </summary>
    private static string NullableClrType(string dataTypeCd, string? format)
    {
        var mapped = TypeMapper.Map(dataTypeCd, format);
        return mapped.IsValueType
            ? mapped.ClrType + "?"   // int? decimal? DateTime? bool?
            : mapped.ClrType + "?";  // string?
    }

    /// <summary>
    /// Converts a service operation name to a valid C# class name.
    /// "ArtSal_GetPrice" → "ArtSal_GetPriceRequest"
    /// </summary>
    private static string ToClassName(string serviceName)
    {
        var id = Regex.Replace(serviceName, @"[^\w]", "_");
        if (id.Length > 0 && char.IsDigit(id[0]))
            id = "_" + id;
        return id + "Request";
    }
}
